version: "3.8"

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management interface
    environment:
      RABBITMQ_DEFAULT_USER: stockmarket
      RABBITMQ_DEFAULT_PASS: supersecret123

  # Stock Publisher (Producer)
  stock-publisher:
    build:
      context: ./stock-publisher
    container_name: stock-publisher
    environment:
      RABBITMQ_URL: amqp://stockmarket:supersecret123@rabbitmq:5672/
      TICKER_INTERVAL: 1000 # Generate messages every 1 second
    depends_on:
      - rabbitmq

  # Consumers
  consumer-aapl:
    build:
      context: ./consumer-aapl
    container_name: consumer-aapl
    environment:
      RABBITMQ_URL: amqp://stockmarket:supersecret123@rabbitmq:5672/
      QUEUE_NAME: AAPL
      MONGODB_URL: mongodb://mongodb-primary:27017,mongodb-secondary:27017,mongodb-arbiter:27018/?replicaSet=rs0
    depends_on:
      - rabbitmq
      - mongodb-primary

  consumer-msft:
    build:
      context: ./consumer-msft
    container_name: consumer-msft
    environment:
      RABBITMQ_URL: amqp://stockmarket:supersecret123@rabbitmq:5672/
      QUEUE_NAME: MSFT
      MONGODB_URL: mongodb://mongodb-primary:27017,mongodb-secondary:27017,mongodb-arbiter:27018/?replicaSet=rs0
    depends_on:
      - rabbitmq
      - mongodb-primary

  consumer-tsla:
    build:
      context: ./consumer-tsla
    container_name: consumer-tsla
    environment:
      RABBITMQ_URL: amqp://stockmarket:supersecret123@rabbitmq:5672/
      QUEUE_NAME: TSLA
      MONGODB_URL: mongodb://mongodb-primary:27017,mongodb-secondary:27017,mongodb-arbiter:27018/?replicaSet=rs0
    depends_on:
      - rabbitmq
      - mongodb-primary

  # MongoDB Primary
  mongodb-primary:
    image: mongo
    container_name: mongodb-primary
    ports:
      - "27017:27017"
    command: mongod --replSet rs0
    volumes:
      - mongo-primary:/data/db

  # MongoDB Secondary
  mongodb-secondary:
    image: mongo
    container_name: mongodb-secondary
    command: mongod --replSet rs0
    volumes:
      - mongo-secondary:/data/db

  # MongoDB Arbiter
  mongodb-arbiter:
    image: mongo
    container_name: mongodb-arbiter
    command: mongod --replSet rs0 --port 27018
    volumes:
      - mongo-arbiter:/data/db

  # Stock Liveview Frontend
  stock-liveview-1:
    build:
      context: ./stock-liveview
    container_name: stock-liveview-1
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://mongodb-primary:27017,mongodb-secondary:27017,mongodb-arbiter:27018/?replicaSet=rs0
    depends_on:
      - mongodb-primary

  stock-liveview-2:
    build:
      context: ./stock-liveview
    container_name: stock-liveview-2
    ports:
      - "3001:3000"
    environment:
      MONGODB_URL: mongodb://mongodb-primary:27017,mongodb-secondary:27017,mongodb-arbiter:27018/?replicaSet=rs0
    depends_on:
      - mongodb-primary

  # NGINX Load Balancer
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stock-liveview-1
      - stock-liveview-2

volumes:
  mongo-primary:
  mongo-secondary:
  mongo-arbiter:
